### ISSUE TITLE
运行报错，然后也收听不到音乐

### ISSUE THREAD

**Issue by zhiweio** [ma6174/fmpi#5]
pi@raspberrypi:~/myProject/fmpi $ sudo ./start.sh
http://0.0.0.0:8080/
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/pi/myProject/fmpi/fmpi.py", line 85, in fmpi
    douban_music = self.get_douban_music()
  File "/home/pi/myProject/fmpi/fmpi.py", line 58, in get_douban_music
    song = douban.getmusic()
  File "/home/pi/myProject/fmpi/douban.py", line 19, in getmusic
    song = json.loads(httpConnection.getresponse().read())['song']
  File "/usr/lib/python2.7/json/__init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
一运行就出现这错，然后打开网页正常显示GET，但是收听不到音乐

**Comment by ghost** [comment]
https://github.com/ma6174/fmpi/pull/6

**Comment by onlinelei** [comment]
同求

**Comment by mikecochen** [comment]
同样问题

**Comment by needhourger** [comment]
+1

**Comment by EsspPao** [comment]
+1，有人知道怎么解决吗
